spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sportvision
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
  verification-url: http://localhost:8080/api/v1/auth/verify