spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

application:
  security:
    jwt:
      secret-key: "ZHVtbXlfc2VjcmV0X2tleV9mb3JfdGVzdGluZ19vbmx5XzEyMzQ1Njc4OTA="
app:
  sendgrid:
    api-key: "dummy_sendgrid_key"
    from-email: "test@sportvision.com"
  telegram:
    bot-token: "dummy_telegram_token"

sportvision:
  stripe:
    secret-key: "sk_test_dummy"
    webhook-secret: "whsec_dummy"